language: r
cache: packages
sudo: required

# r_packages:
#  - sem
#  - qgraph
#  - semPlot

os: 
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - gfortran-7
#- osx

r:
 - oldrel
 - release
 - devel 

install:
 - sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends r-cran-openmx

warnings_are_errors: true    
r_check_args: "--run-dontrun"

# before_install:
#   Rscript -e 'update.packages(ask = FALSE)'